runtime: nodejs
vm: true
service: nodejs-hmac
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.5
#health check is enabled by default, refer https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml    
